[package]
name = "chill"
version = "0.1.0+master"
authors = ["Craig M. Brandenburg <c.m.brandenburg@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Client-side CouchDB library"
repository = "https://github.com/cmbrandenburg/chill-rs"
keywords = ["couchdb", "database", "nosql"]

[dependencies]
