[package]
name = "chill"
version = "0.1.0+master"
authors = ["Craig M. Brandenburg <c.m.brandenburg@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Client-side CouchDB library"
repository = "https://github.com/cmbrandenburg/chill-rs"
keywords = ["couchdb", "database", "nosql"]

[dependencies]
base64 = "0.1"
hyper = "0.8"
mime = "0.2"
regex = "0.1"
serde = "0.7"
serde_json = "0.7"
tempdir = "0.3"
url = "0.5"
uuid = "0.1"
